"use client";

import { ImagePlus, Upload } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Form = { name: string; slug: string; campusName: string; administratorFirstName: string; administratorLastName: string; administratorEmail: string; websiteUrl: string; contactEmail: string; contactPhone: string; address: string; motto: string; mission: string; vision: string; shortAbout: string; primaryColor: string; secondaryColor: string; accentColor: string; logoDataUrl?: string; iconDataUrl?: string };
type ScanDraft = { error?: { message?: string } | string; finalUrl?: string; nameCandidates?: string[]; pagesVisited?: string[]; warnings?: string[]; failedPages?: string[]; mission?: string; vision?: string; description?: string; address?: string; emails?: string[]; phones?: string[]; logoCandidates?: string[]; iconCandidates?: string[]; colorCandidatesDetailed?: { value: string; roleSuggestion?: string; source?: string }[] };
const initial: Form = { name: "", slug: "", campusName: "", administratorFirstName: "", administratorLastName: "", administratorEmail: "", websiteUrl: "", contactEmail: "", contactPhone: "", address: "", motto: "", mission: "", vision: "", shortAbout: "", primaryColor: "#F5D900", secondaryColor: "#0B0B0B", accentColor: "#FFF8C9" };

function Preview({ form }: { form: Form }) { return <div className="overflow-hidden rounded-xl border" style={{ background: form.secondaryColor, color: "#fff" }}><div className="p-6"><div className="flex items-center gap-3">{form.logoDataUrl ? <img src={form.logoDataUrl} alt="School logo preview" className="h-12 w-12 rounded object-contain" /> : <div className="flex h-12 w-12 items-center justify-center rounded font-black" style={{ background: form.primaryColor, color: form.secondaryColor }}>{(form.name || "SCH").slice(0, 3).toUpperCase()}</div>}<div className="font-semibold">{form.name || "Your school name"}</div></div><p className="mt-8 text-sm font-bold uppercase tracking-wider" style={{ color: form.primaryColor }}>{form.motto || "Your school motto"}</p><h3 className="mt-3 text-2xl font-bold">Welcome back</h3><p className="mt-2 text-sm opacity-70">Sign in with your school slug and account details.</p></div></div>; }

function UploadCard({ title, helper, accept, preview, onChange, multiple = false }: { title: string; helper: string; accept: string; preview?: string; onChange: (event: React.ChangeEvent<HTMLInputElement>) => void; multiple?: boolean }) { return <label className="group relative flex min-h-40 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-muted-foreground/25 bg-muted/20 p-5 text-center transition hover:border-primary/60 hover:bg-primary/5 focus-within:ring-2 focus-within:ring-primary"><input className="sr-only" type="file" accept={accept} multiple={multiple} onChange={onChange} />{preview ? <img src={preview} alt={`${title} preview`} className="mb-3 h-20 max-w-full rounded object-contain" /> : <ImagePlus className="mb-3 h-8 w-8 text-muted-foreground" aria-hidden="true" />}<span className="font-medium">{preview ? `Replace ${title.toLowerCase()}` : title}</span><span className="mt-1 text-xs text-muted-foreground">{helper}</span></label>; }

export default function Page() {
  const router = useRouter(); const [step, setStep] = useState(1); const [form, setForm] = useState<Form>(initial); const [screenshots, setScreenshots] = useState<string[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [scanning, setScanning] = useState(false); const [scanStage, setScanStage] = useState("idle"); const [scanDraft, setScanDraft] = useState<ScanDraft | null>(null); const [manualFields, setManualFields] = useState<Set<keyof Form>>(new Set());
  const update = (key: keyof Form, value: string) => { setManualFields(fields => new Set(fields).add(key)); setForm(current => ({ ...current, [key]: value })); };
  const fileAsData = (key: "logoDataUrl" | "iconDataUrl") => (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (!["image/png", "image/jpeg", "image/webp"].includes(file.type) || file.size > 1_500_000) { setError("Use a PNG, JPEG or WEBP image up to 1.5 MB."); return; } const reader = new FileReader(); reader.onload = () => setForm(current => ({ ...current, [key]: String(reader.result) })); reader.readAsDataURL(file); };
  const addScreenshots = (event: React.ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []).slice(0, 3); Promise.all(files.map(file => new Promise<string>(resolve => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(file); }))).then(setScreenshots); };
  async function scan() { setScanning(true); setError(""); setMessage(""); setScanStage("Validating website"); try { setScanStage("Connecting to website"); const response = await fetch("/api/platform-admin/school-import/website", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url: form.websiteUrl }) }); setScanStage("Discovering internal pages and extracting school identity"); const raw = await response.text(); let draft: ScanDraft | null = null; if (raw.trim()) { try { draft = JSON.parse(raw); } catch { throw new Error("Website scan failed before a complete response was received. Please retry."); } } if (!response.ok) { const backendError = typeof draft?.error === "string" ? draft.error : draft?.error?.message; throw new Error(backendError ?? `Website scan failed (HTTP ${response.status}).`); } if (!draft) throw new Error("Website scan failed before a complete response was received. Please retry."); setScanStage("Preparing review draft"); setScanDraft(draft); setForm(current => ({ ...current, name: manualFields.has("name") ? current.name : (draft.nameCandidates?.[0] || current.name), websiteUrl: manualFields.has("websiteUrl") ? current.websiteUrl : (draft.finalUrl || current.websiteUrl), contactEmail: manualFields.has("contactEmail") ? current.contactEmail : (draft.emails?.[0] || current.contactEmail), contactPhone: manualFields.has("contactPhone") ? current.contactPhone : (draft.phones?.[0] || current.contactPhone), address: manualFields.has("address") ? current.address : (draft.address || current.address), mission: manualFields.has("mission") ? current.mission : (draft.mission || current.mission), vision: manualFields.has("vision") ? current.vision : (draft.vision || current.vision), shortAbout: manualFields.has("shortAbout") ? current.shortAbout : (draft.description || current.shortAbout), primaryColor: manualFields.has("primaryColor") ? current.primaryColor : (draft.colorCandidatesDetailed?.find(x => x.roleSuggestion === "primary")?.value || current.primaryColor), secondaryColor: manualFields.has("secondaryColor") ? current.secondaryColor : (draft.colorCandidatesDetailed?.find(x => x.roleSuggestion === "secondary")?.value || current.secondaryColor), accentColor: manualFields.has("accentColor") ? current.accentColor : (draft.colorCandidatesDetailed?.find(x => x.roleSuggestion === "accent")?.value || current.accentColor) })); setMessage(`Website scan completed — ${draft.pagesVisited?.length ?? 0} pages checked. Findings are editable and not saved yet.`); setStep(2); } catch (reason) { setError(reason instanceof Error ? reason.message : "Website scan failed. You can continue manually."); setScanStage("failed"); } finally { setScanning(false); } }
  async function submit(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch("/api/platform-admin/schools", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.name, slug: form.slug, campusName: form.campusName, administratorFirstName: form.administratorFirstName, administratorLastName: form.administratorLastName, administratorEmail: form.administratorEmail }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to create school."); const tenantId = result.school?.summary?.tenantId ?? result.summary?.tenantId; const branding = await fetch(`/api/platform-admin/schools/${tenantId}/branding`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!branding.ok) throw new Error((await branding.json()).error ?? "School created, but branding could not be saved."); router.push(`/super-admin/schools/${tenantId}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create school."); } finally { setSaving(false); } }
  const steps = ["Website & Discovery", "Review School Identity", "Administrator & Access", "Preview & Create"];
  const labels: [keyof Form, string][] = [["contactEmail", "Contact email"], ["contactPhone", "Contact phone"], ["address", "Address"], ["motto", "Motto"], ["primaryColor", "Primary colour"], ["secondaryColor", "Secondary colour"], ["accentColor", "Accent colour"]];
  return <main className="mx-auto max-w-4xl space-y-6 p-8"><header><p className="text-sm text-muted-foreground">Platform onboarding</p><h1 className="text-3xl font-semibold">Add School</h1><p className="mt-2 text-sm text-muted-foreground">Discover the school identity first, then review and create the school.</p></header><div className="flex flex-wrap gap-2 text-sm">{steps.map((label, index) => <div key={label} className={`rounded-full px-3 py-1 ${step === index + 1 ? "bg-primary font-semibold" : "bg-muted text-muted-foreground"}`}>{index + 1}. {label}</div>)}</div><form onSubmit={submit} className="space-y-6 rounded-xl border bg-card p-6">
    {step === 1 && <section className="space-y-6"><div><label className="block space-y-2 text-sm font-medium" htmlFor="website-url">Website URL <span className="font-normal text-muted-foreground">(optional)</span></label><Input id="website-url" type="url" value={form.websiteUrl} onChange={event => update("websiteUrl", event.target.value)} placeholder="https://school.example" /><p className="mt-1 text-xs text-muted-foreground">Scan first to pre-fill the school identity, or continue manually without a website.</p></div><div className="flex flex-wrap gap-3"><Button type="button" onClick={scan} disabled={scanning || !form.websiteUrl}><Upload className="mr-2 h-4 w-4" />{scanning ? "Scanning…" : "Scan Website"}</Button><Button type="button" variant="outline" onClick={() => setStep(2)}>Continue without website</Button></div>{scanning && <div role="status" className="rounded-lg bg-muted p-4 text-sm"><p className="font-semibold">Scanning website</p><p className="mt-1">→ {scanStage}</p><p className="mt-1 text-muted-foreground">The crawler is checking relevant pages and preparing a review draft.</p></div>}<div className="grid gap-4 sm:grid-cols-2"><UploadCard title="Upload school logo" helper="Click to choose · PNG, JPG or WEBP up to 1.5 MB" accept="image/png,image/jpeg,image/webp" preview={form.logoDataUrl || scanDraft?.logoCandidates?.[0]} onChange={fileAsData("logoDataUrl")} /><UploadCard title="Upload favicon" helper="Click to choose · PNG, JPG or WEBP up to 1.5 MB" accept="image/png,image/jpeg,image/webp" preview={form.iconDataUrl || scanDraft?.iconCandidates?.[0]} onChange={fileAsData("iconDataUrl")} /></div><div><p className="mb-2 text-sm font-medium">Reference screenshots <span className="font-normal text-muted-foreground">(up to 3)</span></p><UploadCard title="Add screenshots" helper="Click to choose up to 3 PNG, JPG or WEBP images" accept="image/png,image/jpeg,image/webp" multiple onChange={addScreenshots} />{screenshots.length > 0 && <div className="mt-3 grid grid-cols-3 gap-3">{screenshots.map((image, index) => <img key={`${image}-${index}`} src={image} alt={`Reference screenshot ${index + 1}`} className="h-24 w-full rounded border object-cover" />)}</div>}</div>{scanDraft && <div className="rounded-lg bg-muted p-4 text-sm"><p className="font-semibold">Website scan completed</p><p className="mt-1">{scanDraft.pagesVisited?.length ?? 0} pages checked. Findings will be reviewed in the next step.</p></div>}</section>}
    {step === 2 && <section className="space-y-5"><div><h2 className="text-xl font-semibold">Review School Identity</h2><p className="mt-1 text-sm text-muted-foreground">Review and edit imported values before creating the school.</p></div><label className="block space-y-2 text-sm font-medium">Display name<Input value={form.name} onChange={event => update("name", event.target.value)} /></label><div className="grid gap-4 sm:grid-cols-2">{labels.map(([key, label]) => <label className="block space-y-2 text-sm font-medium" key={key}>{label}{key.endsWith("Color") ? <span className="flex items-center gap-2"><span className="h-8 w-8 shrink-0 rounded border" style={{ backgroundColor: form[key] as string }} /><Input type="text" value={form[key] as string} onChange={event => update(key, event.target.value)} /></span> : <Input value={form[key] as string} onChange={event => update(key, event.target.value)} />}</label>)}</div><div className="grid gap-4">{([["mission", "Mission"], ["vision", "Vision"], ["shortAbout", "About the school"]] as [keyof Form, string][]).map(([key, label]) => <label className="block space-y-2 text-sm font-medium" key={key}>{label}<textarea className="min-h-24 w-full rounded-md border bg-background p-3 text-sm" value={form[key] as string} onChange={event => update(key, event.target.value)} /></label>)}</div></section>}
    {step === 3 && <section className="space-y-5"><div><h2 className="text-xl font-semibold">Administrator &amp; Access</h2><p className="mt-1 text-sm text-muted-foreground">Set the school URL and initial administrator account.</p></div><div className="grid gap-4 sm:grid-cols-2"><label className="block space-y-2 text-sm font-medium">Slug<Input value={form.slug} onChange={event => update("slug", event.target.value)} required /></label><label className="block space-y-2 text-sm font-medium">Campus name<Input value={form.campusName} onChange={event => update("campusName", event.target.value)} required /></label><label className="block space-y-2 text-sm font-medium">Administrator first name<Input value={form.administratorFirstName} onChange={event => update("administratorFirstName", event.target.value)} required /></label><label className="block space-y-2 text-sm font-medium">Administrator last name<Input value={form.administratorLastName} onChange={event => update("administratorLastName", event.target.value)} required /></label><label className="block space-y-2 text-sm font-medium sm:col-span-2">Administrator email<Input type="email" value={form.administratorEmail} onChange={event => update("administratorEmail", event.target.value)} required /></label></div></section>}
    {step === 4 && <section className="space-y-5"><h2 className="text-xl font-semibold">Preview &amp; Create</h2><Preview form={form} /><p className="text-sm text-muted-foreground">Website scanning is advisory. Nothing is finalized until you create the school.</p></section>}
    {message && <p role="status" className="text-sm text-green-700">{message}</p>}{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex justify-between gap-3"><Button type="button" variant="outline" onClick={() => step === 1 ? router.back() : setStep(step - 1)}>{step === 1 ? "Cancel" : "Back"}</Button>{step < 4 ? <Button type="button" onClick={() => setStep(step + 1)}>{step === 1 ? "Review identity" : step === 2 ? "Administrator & access" : "Preview & create"}</Button> : <Button type="submit" disabled={saving}>{saving ? "Creating…" : "Create School"}</Button>}</div>
  </form></main>;
}
