"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PASSWORD_DESCRIPTION, validPassword } from "@/lib/auth/recovery";

type Context = { schoolName: string; schoolSlug: string; email: string; expiresAtUtc: string; status: "valid" | "expired" | "used" };

export default function SetupPage() {
  const router = useRouter(); const [token, setToken] = useState("");
  const [context, setContext] = useState<Context | null>(null); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState("");
  const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [showPassword, setShowPassword] = useState(false);
  useEffect(() => { const supplied = new URLSearchParams(window.location.search).get("token") ?? ""; setToken(supplied); if (!supplied) { setError("This administrator setup link is invalid."); setLoading(false); return; } fetch(`/api/auth/setup?token=${encodeURIComponent(supplied)}`).then(async response => { const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error ?? "This administrator setup link is invalid."); setContext(result); }).catch(reason => setError(reason instanceof Error ? reason.message : "This administrator setup link is invalid.")).finally(() => setLoading(false)); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (!validPassword(password)) { setError(PASSWORD_DESCRIPTION); return; } if (password !== confirm) { setError("Passwords do not match."); return; } setSubmitting(true); try { const response = await fetch("/api/auth/setup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, newPassword: password }) }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error ?? "Unable to complete administrator setup."); router.replace(`/app/${encodeURIComponent(result.tenantSlug)}/login?setup=success`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to complete administrator setup."); } finally { setSubmitting(false); } }
  if (loading) return <main className="flex min-h-screen items-center justify-center p-6"><div role="status" className="max-w-md rounded-xl border bg-card p-8 text-center"><h1 className="text-2xl font-semibold">Setting up your invitation…</h1><p className="mt-2 text-sm text-muted-foreground">Checking your administrator access.</p></div></main>;
  if (error && !context) return <main className="flex min-h-screen items-center justify-center p-6"><div className="max-w-md rounded-xl border bg-card p-8 text-center"><h1 className="text-2xl font-semibold">Administrator setup unavailable</h1><p className="mt-3 text-sm text-red-700">{error}</p><Button className="mt-6" onClick={() => router.push("/login")}>Go to sign in</Button></div></main>;
  if (!context || context.status !== "valid") return <main className="flex min-h-screen items-center justify-center p-6"><div className="max-w-md rounded-xl border bg-card p-8 text-center"><h1 className="text-2xl font-semibold">{context?.status === "used" ? "Setup link already used" : "Setup link expired"}</h1><p className="mt-3 text-sm text-muted-foreground">{context?.status === "used" ? "This setup link has already been used. Sign in with your existing password." : "This administrator setup link has expired. Ask your Platform Administrator to send a new invitation."}</p></div></main>;
  return <main className="flex min-h-screen items-center justify-center bg-muted/30 p-6"><section className="w-full max-w-md rounded-xl border bg-card p-8 shadow-sm"><p className="text-sm text-muted-foreground">Administrator invitation</p><h1 className="mt-2 text-3xl font-semibold">Set up your administrator account</h1><div className="mt-5 rounded-lg bg-muted p-4 text-sm"><p className="font-medium">{context.schoolName}</p><p className="mt-1 text-muted-foreground">{context.email}</p><p className="mt-2 text-muted-foreground">School login code: <span className="font-medium text-foreground">{context.schoolSlug}</span></p></div><p className="mt-6 text-sm text-muted-foreground">Create a password to access your school portal.</p><form onSubmit={submit} className="mt-5 space-y-4"><p className="text-sm text-muted-foreground">{PASSWORD_DESCRIPTION}</p><label className="block space-y-2 text-sm font-medium">New password<div className="flex gap-2"><Input type={showPassword ? "text" : "password"} value={password} onChange={event => setPassword(event.target.value)} autoComplete="new-password" required /><Button type="button" variant="outline" onClick={() => setShowPassword(value => !value)}>{showPassword ? "Hide" : "Show"}</Button></div></label><label className="block space-y-2 text-sm font-medium">Confirm password<Input type={showPassword ? "text" : "password"} value={confirm} onChange={event => setConfirm(event.target.value)} autoComplete="new-password" required /></label>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<Button className="w-full" type="submit" disabled={submitting}>{submitting ? "Setting up account…" : "Set up account"}</Button></form></section></main>;
}
