"use client";
/* The detail view synchronizes its server snapshot when the route tenant changes. */
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { Button } from "@/components/ui/button";
import { PlatformBrandingEditor } from "@/components/platform/platform-branding-editor";
type Details = { summary: { tenantId: string; name: string; slug: string; isActive: boolean; createdAtUtc: string; students: number; staff: number; guardians: number; activatedAccounts: number; activeAdministrators: number; pendingTeacherInvitations: number }; campuses: { id: string; name: string; isActive: boolean }[] };
export default function Page() { const { tenantId } = useParams<{ tenantId: string }>(); const [details, setDetails] = useState<Details | null>(null); const [error, setError] = useState(""); async function load() { const response = await fetch(`/api/platform-admin/schools/${tenantId}`); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Unable to load school."); setDetails(result); } useEffect(() => { load().catch(e => setError(e.message)); }, [tenantId]); async function setStatus(isActive: boolean) { if (!isActive && !window.confirm("Suspend this school? Tenant records will remain preserved.")) return; const response = await fetch(`/api/platform-admin/schools/${tenantId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ isActive }) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "Unable to update school."); return; } await load(); } if (error) return <main className="p-8 text-red-700">{error}</main>; if (!details) return <main className="p-8">Loading school…</main>; const s = details.summary; return <main className="mx-auto max-w-6xl space-y-8 p-8"><header className="flex items-start justify-between"><div><h1 className="text-3xl font-semibold">{s.name}</h1><p className="text-sm text-muted-foreground">{s.slug} · Created {new Date(s.createdAtUtc).toLocaleDateString()}</p></div><Button variant={s.isActive ? "destructive" : "default"} onClick={() => setStatus(!s.isActive)}>{s.isActive ? "Suspend School" : "Reactivate School"}</Button></header><div className="grid gap-4 sm:grid-cols-4">{[["Students",s.students],["Staff",s.staff],["Guardians",s.guardians],["Activated accounts",s.activatedAccounts]].map(([label,value]) => <div className="rounded-xl border bg-card p-5" key={label}><div className="text-xs text-muted-foreground">{label}</div><div className="mt-2 text-2xl font-semibold">{value}</div></div>)}</div><PlatformBrandingEditor tenantId={tenantId} /><section className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Campuses</h2><ul className="mt-3 space-y-2">{details.campuses.map(campus => <li key={campus.id}>{campus.name} <span className="text-xs text-muted-foreground">{campus.isActive ? "Active" : "Inactive"}</span></li>)}</ul><p className="mt-4 text-sm text-muted-foreground">Administrators: {s.activeAdministrators} · Pending teacher invitations: {s.pendingTeacherInvitations}</p></section></main>; }
