"use client";
import { ChangeEvent, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type Branding = { websiteUrl?: string; contactEmail?: string; contactPhone?: string; address?: string; motto?: string; mission?: string; vision?: string; shortAbout?: string; logoDataUrl?: string; iconDataUrl?: string; primaryColor: string; secondaryColor: string; accentColor: string };
const colors = ["primaryColor", "secondaryColor", "accentColor"] as const;
function readImage(event: ChangeEvent<HTMLInputElement>, setValue: (value: string) => void) { const file = event.target.files?.[0]; if (!file || !["image/png", "image/jpeg", "image/webp"].includes(file.type) || file.size > 1_500_000) return; const reader = new FileReader(); reader.onload = () => setValue(String(reader.result)); reader.readAsDataURL(file); }
export function PlatformBrandingEditor({ tenantId }: { tenantId: string }) {
  const [profile, setProfile] = useState<Branding | null>(null); const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/platform-admin/schools/${tenantId}/branding`).then(async response => response.ok ? response.json() : Promise.reject(new Error("load"))).then(setProfile).catch(() => setError("Unable to load school identity.")); }, [tenantId]);
  if (!profile) return null;
  const update = (key: keyof Branding, value: string) => setProfile(current => current ? { ...current, [key]: value } : current);
  async function save() { setMessage(""); setError(""); const response = await fetch(`/api/platform-admin/schools/${tenantId}/branding`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setError(result.error ?? "Unable to save school identity."); return; } setProfile(result); setMessage("School identity saved."); setOpen(false); }
  return <section className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">School profile & branding</h2><p className="text-sm text-muted-foreground">Identity shown on this school’s login experience.</p></div><Button type="button" variant="outline" onClick={() => setOpen(value => !value)}>{open ? "Close editor" : "Edit profile"}</Button></div>{message && <p className="mt-3 text-sm text-green-700">{message}</p>}{error && <p className="mt-3 text-sm text-red-700">{error}</p>}{open && <div className="mt-5 grid gap-4 sm:grid-cols-2">{([['websiteUrl','Website URL'],['contactEmail','Contact email'],['contactPhone','Contact phone'],['address','Address'],['motto','Motto']] as const).map(([key,label]) => <label className="space-y-2 text-sm" key={key}>{label}<Input value={profile[key] ?? ""} onChange={event => update(key, event.target.value)} /></label>)}{colors.map(key => <label className="space-y-2 text-sm" key={key}>{key.replace("Color", " colour")}<span className="flex items-center gap-2"><input type="color" value={/^#[0-9A-Fa-f]{6}$/.test(profile[key]) ? profile[key] : "#ffffff"} onChange={event => update(key, event.target.value.toUpperCase())} className="h-8 w-8" /><span className="h-6 w-6 rounded border" style={{ backgroundColor: profile[key] }} /><Input value={profile[key]} onChange={event => update(key, event.target.value)} /></span></label>)}{([['mission','Mission'],['vision','Vision'],['shortAbout','Short about']] as const).map(([key,label]) => <label className="space-y-2 text-sm sm:col-span-2" key={key}>{label}<textarea className="min-h-20 w-full rounded-md border bg-background p-3 text-sm" value={profile[key] ?? ""} onChange={event => update(key, event.target.value)} /></label>)}<label className="space-y-2 text-sm">Logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={event => readImage(event, value => update("logoDataUrl", value))} />{profile.logoDataUrl && <img src={profile.logoDataUrl} alt="School logo preview" className="h-12 w-12 rounded object-contain" />}</label><label className="space-y-2 text-sm">Icon / favicon<input type="file" accept="image/png,image/jpeg,image/webp" onChange={event => readImage(event, value => update("iconDataUrl", value))} />{profile.iconDataUrl && <img src={profile.iconDataUrl} alt="School icon preview" className="h-10 w-10 rounded object-contain" />}</label><div className="sm:col-span-2"><Button type="button" onClick={save}>Save identity</Button></div></div>}</section>;
}
