"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Branding = { websiteUrl?: string; contactEmail?: string; contactPhone?: string; address?: string; motto?: string; mission?: string; vision?: string; shortAbout?: string; logoDataUrl?: string; iconDataUrl?: string; primaryColor: string; secondaryColor: string; accentColor: string };
const colors = [["primaryColor", "Primary colour"], ["secondaryColor", "Secondary colour"], ["accentColor", "Accent colour"]] as const;

function readImage(event: ChangeEvent<HTMLInputElement>, setValue: (value: string) => void) { const file = event.target.files?.[0]; if (!file || !["image/png", "image/jpeg", "image/webp"].includes(file.type) || file.size > 1_500_000) return; const reader = new FileReader(); reader.onload = () => setValue(String(reader.result)); reader.readAsDataURL(file); }
function BrandUploadCard({ title, preview, onChange }: { title: string; preview?: string; onChange: (event: ChangeEvent<HTMLInputElement>) => void }) { return <label className="group flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-muted-foreground/25 bg-muted/20 p-4 text-center transition hover:border-primary/60 hover:bg-primary/5 focus-within:ring-2 focus-within:ring-primary"><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={onChange} />{preview ? <img src={preview} alt={`${title} preview`} className="mb-2 h-16 w-16 rounded object-contain" /> : <span className="mb-2 text-2xl text-muted-foreground" aria-hidden="true">＋</span>}<span className="text-sm font-medium">{preview ? `Replace ${title.toLowerCase()}` : `Upload ${title.toLowerCase()}`}</span><span className="mt-1 text-xs text-muted-foreground">Click to choose · PNG, JPG or WEBP up to 1.5 MB</span></label>; }

export function PlatformBrandingEditor({ tenantId }: { tenantId: string }) {
  const [profile, setProfile] = useState<Branding | null>(null); const [open, setOpen] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { fetch(`/api/platform-admin/schools/${tenantId}/branding`).then(async response => response.ok ? response.json() : Promise.reject(new Error("load"))).then(setProfile).catch(() => setError("Unable to load school identity.")); }, [tenantId]);
  if (!profile) return null;
  const update = (key: keyof Branding, value: string) => setProfile(current => current ? { ...current, [key]: value } : current);
  async function save() { setMessage(""); setError(""); const response = await fetch(`/api/platform-admin/schools/${tenantId}/branding`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setError(typeof result.error === "string" ? result.error : result.error?.message ?? "Unable to save school identity."); return; } setProfile(result); setMessage("School identity saved."); setOpen(false); }
  return <section className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold">School profile & branding</h2><p className="text-sm text-muted-foreground">Identity shown on this school’s login experience.</p></div><Button type="button" variant="outline" onClick={() => setOpen(value => !value)}>{open ? "Close editor" : "Edit profile"}</Button></div>{message && <p className="mt-3 text-sm text-green-700">{message}</p>}{error && <p className="mt-3 text-sm text-red-700">{error}</p>}{open && <div className="mt-5 grid gap-4 sm:grid-cols-2">{([["websiteUrl", "Website URL"], ["contactEmail", "Contact email"], ["contactPhone", "Contact phone"], ["address", "Address"], ["motto", "Motto"]] as const).map(([key, label]) => <label className="space-y-2 text-sm" key={key}>{label}<Input value={profile[key] ?? ""} onChange={event => update(key, event.target.value)} /></label>)}{colors.map(([key, label]) => <label className="space-y-2 text-sm" key={key}>{label}<span className="flex items-center gap-2"><input type="color" value={/^#[0-9A-Fa-f]{6}$/.test(profile[key]) ? profile[key] : "#ffffff"} onChange={event => update(key, event.target.value.toUpperCase())} className="h-8 w-8" /><span className="h-6 w-6 rounded border" style={{ backgroundColor: profile[key] }} /><Input value={profile[key]} onChange={event => update(key, event.target.value)} /></span></label>)}{([["mission", "Mission"], ["vision", "Vision"], ["shortAbout", "About the school"]] as const).map(([key, label]) => <label className="space-y-2 text-sm sm:col-span-2" key={key}>{label}<textarea className="min-h-20 w-full rounded-md border bg-background p-3 text-sm" value={profile[key] ?? ""} onChange={event => update(key, event.target.value)} /></label>)}<BrandUploadCard title="School logo" preview={profile.logoDataUrl} onChange={event => readImage(event, value => update("logoDataUrl", value))} /><BrandUploadCard title="Favicon" preview={profile.iconDataUrl} onChange={event => readImage(event, value => update("iconDataUrl", value))} /><div className="sm:col-span-2"><Button type="button" onClick={save}>Save identity</Button></div></div>}</section>;
}
