using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SchoolPlatform.Domain.Fees;

namespace SchoolPlatform.Infrastructure.Persistence.Configurations.Fees;

public sealed class DiscountDefinitionConfiguration : IEntityTypeConfiguration<DiscountDefinition>
{ public void Configure(EntityTypeBuilder<DiscountDefinition> b) { b.ToTable("discount_definitions"); b.HasKey(x => x.Id); b.Property(x => x.Name).HasMaxLength(150).IsRequired(); b.Property(x => x.Description).HasMaxLength(500); b.Property(x => x.DefaultAmount).HasPrecision(18,2); b.HasIndex(x => new { x.TenantId, x.Name }).IsUnique(); } }
public sealed class DiscountApplicationConfiguration : IEntityTypeConfiguration<DiscountApplication>
{ public void Configure(EntityTypeBuilder<DiscountApplication> b) { b.ToTable("discount_applications"); b.HasKey(x => x.Id); b.Property(x => x.AmountOverride).HasPrecision(18,2); b.Property(x => x.IdempotencyKey).HasMaxLength(200); b.HasIndex(x => new { x.TenantId, x.DiscountDefinitionId, x.AcademicSessionId, x.AcademicTermId, x.Status }); b.HasIndex(x => new { x.TenantId, x.IdempotencyKey }).IsUnique(); b.HasOne<DiscountDefinition>().WithMany().HasForeignKey(x => x.DiscountDefinitionId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class StudentDiscountAssignmentConfiguration : IEntityTypeConfiguration<StudentDiscountAssignment>
{ public void Configure(EntityTypeBuilder<StudentDiscountAssignment> b) { b.ToTable("student_discount_assignments"); b.HasKey(x => x.Id); b.Property(x => x.AppliedAmount).HasPrecision(18,2); b.HasIndex(x => new { x.TenantId, x.DiscountApplicationId, x.StudentId }).IsUnique(); b.HasIndex(x => new { x.TenantId, x.StudentId, x.AcademicSessionId, x.AcademicTermId }); b.HasOne<DiscountDefinition>().WithMany().HasForeignKey(x => x.DiscountDefinitionId).OnDelete(DeleteBehavior.Restrict); b.HasOne<DiscountApplication>().WithMany().HasForeignKey(x => x.DiscountApplicationId).OnDelete(DeleteBehavior.Restrict); b.HasOne<SchoolPlatform.Domain.Students.Student>().WithMany().HasForeignKey(x => x.StudentId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class StudentFeeAdjustmentConfiguration : IEntityTypeConfiguration<StudentFeeAdjustment>
{ public void Configure(EntityTypeBuilder<StudentFeeAdjustment> b) { b.ToTable("student_fee_adjustments"); b.HasKey(x => x.Id); b.Property(x => x.Amount).HasPrecision(18,2); b.Property(x => x.Description).HasMaxLength(250).IsRequired(); b.Property(x => x.Reason).HasMaxLength(500); b.Property(x => x.ReversalReason).HasMaxLength(500); b.HasIndex(x => new { x.TenantId, x.StudentId, x.AcademicSessionId, x.AcademicTermId }); b.HasOne<SchoolPlatform.Domain.Students.Student>().WithMany().HasForeignKey(x => x.StudentId).OnDelete(DeleteBehavior.Restrict); } }
public sealed class CarryForwardRunConfiguration : IEntityTypeConfiguration<CarryForwardRun>
{ public void Configure(EntityTypeBuilder<CarryForwardRun> b) { b.ToTable("carry_forward_runs"); b.HasKey(x => x.Id); b.Property(x => x.IdempotencyKey).HasMaxLength(200).IsRequired(); b.HasIndex(x => new { x.TenantId, x.IdempotencyKey }).IsUnique(); } }
public sealed class CarryForwardEntryConfiguration : IEntityTypeConfiguration<CarryForwardEntry>
{ public void Configure(EntityTypeBuilder<CarryForwardEntry> b) { b.ToTable("carry_forward_entries"); b.HasKey(x => x.Id); b.Property(x => x.Amount).HasPrecision(18,2); b.HasIndex(x => new { x.TenantId, x.CarryForwardRunId, x.StudentId }).IsUnique(); b.HasIndex(x => new { x.TenantId, x.StudentId, x.SourceSessionId, x.SourceTermId, x.TargetSessionId, x.TargetTermId }); b.HasOne<CarryForwardRun>().WithMany().HasForeignKey(x => x.CarryForwardRunId).OnDelete(DeleteBehavior.Cascade); b.HasOne<SchoolPlatform.Domain.Students.Student>().WithMany().HasForeignKey(x => x.StudentId).OnDelete(DeleteBehavior.Restrict); } }
